### ISSUE TITLE
2回

### ISSUE THREAD

**Issue by t180019** [nc2020/2-t180019#2]
image.png
![image](https://user-images.githubusercontent.com/49541533/79720090-da1ddd00-831a-11ea-8bf6-d44087fcd741.png)
\begin{equation}
18782+18782=3756 \%
\end{equation}

**Comment by t180019** [comment]
![image](https://user-images.githubusercontent.com/49541533/79720270-2f59ee80-831b-11ea-8d7a-03a42172e2c1.png)

**Comment by t180019** [comment]
![image](https://user-images.githubusercontent.com/49541533/80165961-b064fe80-8617-11ea-8a40-178e3c78be18.png)

**Comment by t180019** [comment]
![image](https://user-images.githubusercontent.com/49541533/80165977-b9ee6680-8617-11ea-8c84-cb9376d9b7cd.png)

**Comment by t180019** [comment]
\begin{equation}
4+1=5
\end{equation}

**Comment by junta-m** [comment]
もう少し複雑な式にしてください。

**Comment by t180019** [comment]
1+1=2などで許可が出ている人との違いわ何でしょうか

**Comment by t180019** [comment]
![image](https://user-images.githubusercontent.com/49541533/80854875-84302a00-8c76-11ea-81a0-aef76dcb9c80.png)
![image](https://user-images.githubusercontent.com/49541533/80854880-885c4780-8c76-11ea-824e-2268f2943f53.png) 
\begin{equation}
a x^{2}+b x+c=0
\end{equation}

**Comment by junta-m** [comment]
GitHub には、コメントやレビューによって、プロダクトの質を向上させるという思想があります。そういった観点からコメントしています。許すとか許さないといった観点ではないです。私のコメントではなく、他の人の例を取り入れても、もちろん全く問題ありません。しかしながら、1+1=2 を取り入れたいとは思わないですよね? 自分がどうしたいかで考えると良いと思います。

**Comment by t180019** [comment]
分かりました。
先ほどの物でもダメでしょうか
